#!/bin/sh
### BEGIN INIT INFO
# Provides:          supply
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/app/bin:/app
DESC=SupplyMeter

set -e

source obc_common.sh

startService(){
    SupplyMeterService\
        -p 3014 \
        --hw-version ObcNxg \
        -c $OBC_OBCCONF_FILE \
        --log-file $OBC_LOG_PATH/ss \
        --update-rate 1 \
        --dump $OBC_LOG_PATH/supply_$(date +%Y%m%d_%H%M).dump \
        /dev/null  >> $OBC_LOG_PATH/el_ss_$(date +%Y%m%d_%H%M).log 2>&1 &
        pid=$!
        printAllPid SupplyMeter
}

case $1 in
  start)
        echo -n "Starting ${DESC}: "
        startService
  ;;
  stop)
        echo "Stopping ${DESC}: "
        ps -e | grep ${DESC}
        pkill ${DESC}
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  status)
        ps -e | grep ${DESC}
   ;;
   *)
        echo "Usage: ${DESC} {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim:noet
