#!/bin/sh
### BEGIN INIT INFO
# Provides:          utilities
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/app/bin:/app
DESC=synclogs.sh
set -e

source obc_common.sh

case $1 in
  start)
        echo "start sync $(date)" >> /mnt/log/startrsync.log 2>&1 
        echo "Starting ${DESC}: " >> /mnt/log/startrsync.log 2>&1
        ${DESC} >> /mnt/log/startrsync.log  2>&1 &
  ;;
  stop)
        echo "Stopping ${DESC}: "
        ps -e | grep ${DESC}
        pkill ${DESC}
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  status)
        ps -e | grep ${DESC}
   ;;
   *)
        echo "Usage: ${DESC} {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim:noet

