#!/bin/sh
### BEGIN INIT INFO
# Provides:          mobile
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/app/bin:/app
DESC=MobileService

set -e

source obc_common.sh

startService(){
    MobileService\
        -p 3007 \
        -c $OBC_OBCCONF_FILE \
        --log-file $OBC_LOG_PATH/ms \
        --update-rate 1 \
        --hw-version ObcNxg \
        --mqtt.root_ca_name $OBC_CA_FILE \
        --dump $OBC_LOG_PATH/ms.dump \
        /dev/huaweiMobile  >> $OBC_LOG_PATH/el_ms.log 2>&1 &
        pid=$!
        printAllPid MobileService
}

case $1 in
  start)
        echo -n "Starting ${DESC}: "
        startService
  ;;
  stop)
        echo "Stopping ${DESC}: "
        ps -e | grep ${DESC}
        pkill ${DESC}
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  status)
        ps -e | grep ${DESC}
   ;;
   *)
        echo "Usage: ${DESC} {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim:noet
