#!/bin/sh
### BEGIN INIT INFO
# Provides:          obcagent
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/app/bin:/app
DESC=OBCAgent

set -e

source obc_common.sh

startService(){
    OBCAgent \
        -c $OBC_OBCCONF_FILE \
        --obd-path $OBC_LOG_PATH \
        --obc.ip_backbone 192.168.1.110 \
        --obc.ip_fin 192.168.1.112 \
        --log-level warning \
        --aaem-path $OBC_ERROR_CONF_FILE \
        --mqtt.root_ca_name $OBC_CA_FILE \
        --log-file $OBC_LOG_PATH/agent >> $OBC_LOG_PATH/el_obd_$(date +%Y%m%d_%H%M).log 2>&1 &
        pid=$!
        echo "PID $pid"
}

case $1 in
  start)
        echo -n "Starting ${DESC}: "
        PID=$(pidof $DESC || true)
        if [[ -n "$PID" ]]; then
          echo "Process already running with PID $PID"
        else
          startService
        fi
  ;;
  stop)
        echo -n "Stopping ${DESC}: "
        PID=$(pidof $DESC || true)
        if [[ -n "$PID" ]]; then
          echo "PID $PID"
          kill $PID
        else
          echo "No running process found"
        fi
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  status)
        echo -n "Status ${DESC}: "
        PID=$(pidof $DESC || true)
        if [[ -n "$PID" ]]; then
          echo "RUNNING with PID ${PID}"
        else
          echo "NOT RUNNING"
        fi
   ;;
   *)
        echo "Usage: ${DESC} {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

# vim:noet
