alias ll='ls -alg'
alias l='ls'
alias ..='cd ..'
alias md=mkdir
alias rd=rmdir
alias ro='mount / -o remount,ro'
alias rw='mount / -o remount,rw'

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
